### ISSUE TITLE
Assignment5

### ISSUE THREAD

**Issue by vkats-spbu** [kayumov-24B81/HomeAssignments#23]
Исправил ошибку в последнем коммите

_Originally posted by @kayumov-24B81 in https://github.com/kayumov-24B81/HomeAssignments/issues/21#issuecomment-2544150477_
            
<pre><font color="#26A269"><b>victor@victor-VirtualBox</b></font>:<font color="#12488B"><b>~/accesment/kayumov-24B81/HomeAssignments/Assignment5</b></font>$ make test
g++ -I. -std=c++17 -Werror -Wpedantic -Wall -g -fPIC   -c -o test-transformer.o test-transformer.cpp
<b>test-transformer.cpp:</b> In member function ‘<b>virtual void Interclass_virtual_functions_w_typed_ptrs_Test::TestBody()</b>’:
<b>test-transformer.cpp:278:22:</b> <font color="#C01C28"><b>error: </b></font>comparison of integer expressions of different signedness: ‘<b>int</b>’ and ‘<b>std::vector&lt;Transformer*&gt;::size_type</b>’ {aka ‘<b>long unsigned int</b>’} [<font color="#C01C28"><b>-Werror=sign-compare</b></font>]
  278 |     for(int i = 0; <font color="#C01C28"><b>i &lt; squad.size()</b></font>; ++i)
      |                    <font color="#C01C28"><b>~~^~~~~~~~~~~~~~</b></font>
<b>test-transformer.cpp:284:22:</b> <font color="#C01C28"><b>error: </b></font>comparison of integer expressions of different signedness: ‘<b>int</b>’ and ‘<b>std::vector&lt;Transformer*&gt;::size_type</b>’ {aka ‘<b>long unsigned int</b>’} [<font color="#C01C28"><b>-Werror=sign-compare</b></font>]
  284 |     for(int i = 0; <font color="#C01C28"><b>i &lt; squad.size()</b></font>; ++i)
      |                    <font color="#C01C28"><b>~~^~~~~~~~~~~~~~</b></font>
<b>test-transformer.cpp:286:9:</b> <font color="#C01C28"><b>error: </b></font>deleting object of polymorphic class type ‘<b>Transformer</b>’ which has non-virtual destructor might cause undefined behavior [<font color="#C01C28"><b>-Werror=delete-non-virtual-dtor</b></font>]
  286 |         <font color="#C01C28"><b>delete squad[i]</b></font>;
      |         <font color="#C01C28"><b>^~~~~~~~~~~~~~~</b></font>
cc1plus: all warnings being treated as errors
make: *** [&lt;builtin&gt;: test-transformer.o] Error 1
</pre>

**Comment by kayumov-24B81** [comment]
Исправил эту ошибку последнем коммите.
