### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by MarryAnt** [kayumov-24B81/HomeAssignments#25]
По условию задания необходимо:
1) Протестировать используемые методы **явно**
2) Протестировать вызов методов из **указателя, типизированного предком**
3) Протестировать **в цикле** - _выполнено_

**Comment by kayumov-24B81** [comment]
Здравствуйте. Я не понимаю условие явного тестирования, так как от примера в презентации моя реализация отличается только тем что я проверяю возвращаемое функцией значение. А вызов методов из указателя, типизированного предком реализовывается в тестах под названием virtual_functions_w_typed_ptr, созданных для каждого класса. Является ли в данном случае проблемой именно код или то что все в одном файле?

**Comment by MarryAnt** [comment]
Спасибо, увидела. Тесты для 5 задания идут вразнобой с тестами для 4 задания. Все в порядке, зачтено.
